//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungensAndDragonsGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNDEntities : DbContext
    {
        public DNDEntities()
            : base("name=DNDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JSONStorage> JSONStorage { get; set; }
        public virtual DbSet<TableClass> TableClass { get; set; }
        public virtual DbSet<TableRace> TableRace { get; set; }
        public virtual DbSet<TableSubClass> TableSubClass { get; set; }
        public virtual DbSet<TableSubRace> TableSubRace { get; set; }
    }
}
