//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungensAndDragonsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableRace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableRace()
        {
            this.TableSubRace = new HashSet<TableSubRace>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Speed { get; set; }
        public string AdditionalInfo { get; set; }
        public string AdditionHitPoints { get; set; }
        public string DESCRIPTION { get; set; }
        public string ABILITYBONUS { get; set; }
        public string ABILITYOPTBONUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableSubRace> TableSubRace { get; set; }
    }
}
